# Generated by Django 4.2.3 on 2023-07-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatsMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customerId", models.IntegerField()),
                ("type", models.CharField(max_length=1)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=8)),
                ("uuid", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
