# Generated by Django 4.2.3 on 2023-07-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserStats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="statsmessage", name="id",),
        migrations.AlterField(
            model_name="statsmessage",
            name="customerId",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
